apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: frontend-nextjs
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "256Mi"
              cpu: "700m"
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_BACKEND_API
              valueFrom:
                configMapKeyRef:
                  name: frontend-configmap
                  key: backend_url
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 3000